const Geos = [
  {value: 'US', name: 'your region'},
  {value: 'AR', name: 'Argentina'},
  {value: 'AT', name: 'Austria'},
  {value: 'AU', name: 'Australia'},
  {value: 'BE', name: 'Belgium'},
  {value: 'BR', name: 'Brazil'},
  {value: 'CA', name: 'Canada'},
  {value: 'CH', name: 'Switzerland'},
  {value: 'CL', name: 'Chile'},
  {value: 'DE', name: 'Germany'},
  {value: 'DK', name: 'Denmark'},
  {value: 'EG', name: 'Egypt'},
  {value: 'FI', name: 'Finland'},
  {value: 'FR', name: 'France'},
  {value: 'GB', name: 'United Kingdom'},
  {value: 'GR', name: 'Greece'},
  {value: 'HK', name: 'Hong Kong'},
  {value: 'ID', name: 'Indonesia'},
  {value: 'IE', name: 'Ireland'},
  {value: 'IL', name: 'Israel'},
  {value: 'IN', name: 'India'},
  {value: 'IT', name: 'Italy'},
  {value: 'JP', name: 'Japan'},
  {value: 'KE', name: 'Kenya'},
  {value: 'KR', name: 'South Korea'},
  {value: 'MX', name: 'Mexico'},
  {value: 'NO', name: 'Norway'},
  {value: 'NZ', name: 'New Zealand'},
  {value: 'PH', name: 'Philippines'},
  {value: 'PL', name: 'Poland'},
  {value: 'PT', name: 'Portugal'},
  {value: 'RU', name: 'Russia'},
  {value: 'SE', name: 'Sweden'},
  {value: 'SG', name: 'Singapore'},
  {value: 'TH', name: 'Thailand'},
  {value: 'TR', name: 'Turkey'},
  {value: 'TW', name: 'Taiwan'},
  {value: 'UA', name: 'Ukraine'},
  {value: 'US', name: 'United States'},
  {value: 'VN', name: 'Vietnam'},
  {value: 'ZA', name: 'South Africa'},
];

export default Geos;